name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildAndTestCore:
    name: Build & Test Core
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install Core Dependencies
      run: dotnet restore core/core.csproj
    - name: Build Core
      run: dotnet build core/core.csproj --configuration Release --no-restore
    - name: Test Core
      run: dotnet test core/core.csproj --no-restore --verbosity normal
      
  buildAndTestStandard:
    name: Build & Test Standard
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install Standard Dependencies
      run: dotnet restore standard/standard.csproj
    - name: Build Standard
      run: dotnet build standard/standard.csproj --configuration Release --no-restore
    - name: Test Standard
      run: dotnet test standard/standard.csproj --no-restore --verbosity normal
