name: Build Unity

on:
  push

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  requestManualActivationFile:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v1

      # Request manual activation file
      - name: Request manual activation file
        uses: game-ci/unity-request-activation-file@v2.0-alpha-1
        id: getManualLicenseFile

      # Upload artifact (Unity_v20XX.X.XXXX.alf)
      - name: Expose as artifact
        uses: actions/upload-artifact@v1
        with:
          name: Manual Activation File
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Unity - Activate
        uses: game-ci/unity-activate@v1.3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      - uses: game-ci/unity-builder@v2.0-alpha-6
        with:
          unityVersion: 2019.2.11f1
          targetPlatform: StandaloneWindows64
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
